fluidsurf/apps/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('productos', views.productos, name='productos'),
    path('compras', views.compras, name='compras'),
    path('zonas', views.zonas, name='zonas'),
    path('usuarios', views.usuarios, name='usuarios'),
    path('denuncias', views.denuncias, name='denuncias'),
    path('validar', views.validar, name='validar'),
    path('solicitud', views.solicitud, name='solicitudes'),
    path('perfil/<id>', views.perfil, name='perfil_admin'),
    path('watermark', views.watermark, name='watermark'),

    # Dashboard de fotografo
    path('fotografo', views.fotografo, name='fotografo'),
    path('fotografo-productos', views.fotografo_productos, name='fotografo-productos'),
    path('fotografo-compras', views.fotografo_compras, name='fotografo-compras'),
]

fluidsurf/urls.py
""" fluidsurf URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fluidsurf.apps.home.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('fluidsurf.apps.users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/', include('fluidsurf.apps.dashboard.urls')),
    path('payments/', include('fluidsurf.apps.payments.urls')),
    path('accounts/', include('allauth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fluidsurf/apps/dashboard/models.py
from django.db import models

# Create your models here.



class RegistroCompras(models.Model):
    compras = models.CharField(max_length=10)

    fecha = models.DateField()

    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, related_name='user_registro', null=True)

    def __str__(self):
        return 'RegistroCompras-' + str(self.fecha)

    class Meta:
        verbose_name_plural = 'Registros de Compras'


class RegistroFotografos(models.Model):
    users = models.CharField(max_length=10)

    fecha = models.DateField()

    def __str__(self):
        return 'RegistroFotografos-' + str(self.fecha)

    class Meta:
        verbose_name_plural = 'Registros de Fotografos'


class RegistroSurferos(models.Model):
    users = models.CharField(max_length=10)

    fecha = models.DateField()

    def __str__(self):
        return 'RegistroSurferos-' + str(self.fecha)

    class Meta:
        verbose_name_plural = 'Registros de Surferos'

fluidsurf/apps/home/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField

from fluidsurf.apps.users.models import CustomUser
from django_google_maps.fields import AddressField, GeoLocationField

AREA_CHOICES = (
    ('Europe', _("Europe")),
    ('Africa', _("Africa")),
    ('Asia', _("Asia")),
    ('Oceania', _("Oceania")),
    ('North America', _("North America")),
    ('South America', _("South America"))
)

DEV_REASON_CHOICES = (
    ('Dead on Arrival', _("Dead on Arrival")),
    ('Faulty', _("Faulty, please supply details")),
    ('Order Error', _("Order Error")),
    ('Other', _("Other, please supply details")),
    ('Wrong Item', _("Received Wrong Item"))
)

# Spots
class Continente(models.Model):
    nombre = models.CharField(max_length=25, choices=AREA_CHOICES, default='Europa')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Continente'


class Pais(models.Model):
    nombre = models.CharField(max_length=25)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE, related_name='pais', default='')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'


class Area(models.Model):
    nombre = models.CharField(max_length=25)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, related_name='area', default='')

    def __str__(self):
        return self.nombre


class Spot(models.Model):
    nombre = models.CharField(max_length=25)
    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name='spot', default='')

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    id = models.AutoField(primary_key=True)

    nombre = models.CharField(max_length=100)
    precio = models.IntegerField()

    fecha = models.DateField()
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE, related_name='producto_spot')

    descripcion = models.CharField(max_length=50, blank=True)

    imagen0 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen1 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen2 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen3 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen4 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen5 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen6 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen7 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen8 = models.ImageField(upload_to="img/productos/", blank=True)
    imagen9 = models.ImageField(upload_to="img/productos/", blank=True)

    stock = models.IntegerField(default=1)

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='producto')

    def __str__(self):
        return self.nombre


class Compra(models.Model):
    comprador = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='compra_c', default='')
    vendedor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='compra_v', default='')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='compra_p', default='')
    descargas = models.IntegerField(default=3)
    fecha = models.DateField()

    def __str__(self):
        return str(self.vendedor) + "-" + str(self.comprador) + str(self.fecha)


class Denuncia(models.Model):
    CHOICES = (
        ('MAL USO', _("Bad usage of the app")),
        ('INAPROPIADO', _("Innapropiate content")),
        ('SPAM', _("Spam")),
        ('OTRO', _("Other")),
    )

    emisor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='denuncia_e', default='')
    receptor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='denuncia_r', default='')
    motivo = models.CharField(max_length=30, choices=CHOICES, default='MAL USO')
    detalles = models.CharField(max_length=200)

    def __str__(self):
        return self.receptor.username + '-' + self.emisor.username + '-' + str(datetime.date.today())


# PAGINAS DE INFORMACION DEL FOOTER
class Terms(models.Model):
    text = HTMLField(max_length=45000,
                     default="Terminos y condiciones de uso...",
                     help_text="Este es el texto que aparecera en la seccion terminos y condiciones")

    text_en = HTMLField(max_length=45000,
                     default="Terms and conditions...",
                     help_text="This is the text that will appear on your terms and conditions section")
    class Meta:
        verbose_name_plural = 'Terminos y Condiciones'

    def __str__(self):
        return 'Terminos&Condiciones-' + str(datetime.date.today())


class Privacy(models.Model):
    text = HTMLField(max_length=45000,
                     default="Politica de privacidad...",
                     help_text="Este es el texto que aparecera en la seccion politica de privacidad")

    text_en = HTMLField(max_length=45000,
                     default="Privacy policy...",
                     help_text="This is the text that will appear on your policy privacy section")

    class Meta:
        verbose_name_plural = 'Politica de Privacidad'

    def __str__(self):
        return 'Politica de privacidad-' + str(datetime.date.today())


class Taxes(models.Model):
    text = HTMLField(max_length=45000,
                     default="Impuestos y facturacion...",
                     help_text="Este es el texto que aparecera en la seccion impuestos y facturacion")

    text_en = HTMLField(max_length=45000,
                     default="Taxes and billing...",
                     help_text="This is the text that will appear on your taxes & billing section")

    class Meta:
        verbose_name_plural = 'Impuestos y facturacion'

    def __str__(self):
        return 'ImpuestosyFacturacion-' + str(datetime.date.today())


class FreeSub(models.Model):
    text = HTMLField(max_length=45000,
                     default="Suscripcion gratuita...",
                     help_text="Este es el texto que aparecera en la seccion suscripcion gratuita")

    text_en = HTMLField(max_length=45000,
                        default="Free subscription features...",
                        help_text="This is the text that will appear on your free subcription features section")

    class Meta:
        verbose_name_plural = 'Suscripcion gratuita'

    def __str__(self):
        return 'Suscripciongratuita-' + str(datetime.date.today())


class Copyright(models.Model):
    text = HTMLField(max_length=45000,
                     default="Copyright, licencias y tamaños...",
                     help_text="Este es el texto que aparecera en la seccion copyright, licencias y tamaños")

    text_en = HTMLField(max_length=45000,
                        default="Copyright, licenses and sizes...",
                        help_text="This is the text that will appear on your copyright, licenses and sizes section")

    class Meta:
        verbose_name_plural = 'Copyright, licencias y tamaños'

    def __str__(self):
        return 'Copyright-' + str(datetime.date.today())


class SecurePayments(models.Model):

    image = models.ImageField(upload_to='img/information/', blank=True)

    text = HTMLField(max_length=45000,
                     default="Seguridad en pagos...",
                     help_text="Este es el texto que aparecera en la seccion seguridad en pagos")

    text_en = HTMLField(max_length=45000,
                        default="Secure payments...",
                        help_text="This is the text that will appear on your secure payments section")

    class Meta:
        verbose_name_plural = 'Seguridad en pagos'

    def __str__(self):
        return 'Seguridadenpagos-' + str(datetime.date.today())


class Manual(models.Model):
    text = HTMLField(max_length=45000,
                     default="Instrucciones: vender fotos...",
                     help_text="Este es el texto que aparecera en la seccion instrucciones: vender fotos")

    text_en = HTMLField(max_length=45000,
                        default="Selling photos: manual...",
                        help_text="This is the text that will appear on your selling photos: manual section")

    class Meta:
        verbose_name_plural = 'Instrucciones: vender fotos'

    def __str__(self):
        return 'Instrucciones-' + str(datetime.date.today())


class HowDoesItWork(models.Model):
    text = HTMLField(max_length=45000,
                     default="Como funciona...",
                     help_text="Este es el texto que aparecera en la seccion como funciona")

    text_en = HTMLField(max_length=45000,
                        default="How does it work...",
                        help_text="This is the text that will appear on your how does it work section")

    image = models.ImageField(upload_to='img/information/', blank=True)

    text2 = HTMLField(max_length=45000,
                     default="2 Como funciona...",
                     help_text="Este es el texto que aparecera en la seccion como funciona")

    text2_en = HTMLField(max_length=45000,
                        default=" How does it work...",
                        help_text="This is the text that will appear on your how does it work section")

    class Meta:
        verbose_name_plural = '¿Como funciona?'

    def __str__(self):
        return 'Comofunciona-' + str(datetime.date.today())


class SolicitudStock(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='solicitud_u')
    product = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='solicitud_p')

    class Meta:
        verbose_name_plural = 'Solicitudes de Stock'

    def __str__(self):
        return self.user.username + "-" + self.product.nombre


class Devolucion(models.Model):

templates/dashboard/compras.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load i18n %}

{% block main %}

        <style>
        #id_comprador__username, #id_vendedor__username, #id_fecha {
            height: 50px;
            border-radius: 5px;
            box-shadow: none;
            border: 1px solid gainsboro;
            padding-left: 10px;
            background: white;
        }
    </style>

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">{% trans 'Home' %}</a></li>
              <li class="breadcrumb-item active">Gestión comercial</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
       <div class="row">
          <div class="col-1"></div>
              <div class="col-11">
                  <div class="col-12" style="position: relative; left: 100px;"><i class="fas fa-filter"></i> Filtrar</div>
                  <form id="filter_form" action="" method="get" class="row" style="position: relative; left: 112px;">
                        <div class="col-12 col-lg-2 mt-3">{{ filter.form.comprador__username }}</div>
                        <div class="col-12 col-lg-2 mt-3">{{ filter.form.vendedor__username  }}</div>
                        <div class="col-12 col-lg-8 mt-3">{{ filter.form.fecha }}</div>
                      <input type="submit" value="Aplicar filtros" class="btn btn-primary mt-3 ml-2">
                  </form>
              </div>
          </div>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
<div class="container">
    <div class="row">
       <div class="card col-12">
              <div class="card-header border-transparent">
                <h3 class="card-title">Compras</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table m-0">
                    <thead>
                    <tr>
                      <th>ID del Pedido</th>
                      <th>Fecha</th>
                      <th>Producto</th>
                      <th>Comprador</th>
                      <th>Vendedor</th>
                    </tr>
                    </thead>
                    <tbody>
                      {% for compra in filter.qs %}
                          <tr>
                            <td><a href="{% url 'admin:home_compra_change' compra.id %}">OR{{ compra.id }}</a></td>
                            <td>{{ compra.fecha|date:"d M Y" }}</td>
                            <td>{{ compra.producto.nombre }}</td>
                            <td><a href="{% url 'perfil_admin' id=compra.comprador.id %}">{{ compra.comprador }}</a></td>
                            <td><a href="{% url 'perfil_admin' id=compra.vendedor.id %}">{{ compra.vendedor }}</a></td>
                          </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">

                <a href="{% url 'admin:home_compra_changelist' %}" class="btn btn-sm btn-secondary float-right">Gestionar compras</a>

                  <form method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-sm btn-success float-left ml-3"> <i class="fas fa-file-export"></i>Exportar a Excel</button>
                  </form>

                  <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                      <label for="fileInput" style="cursor: pointer;">
                          <span class="btn btn-sm btn-info float-left ml-3">
                              <i class="fas fa-file-import"></i>Importar desde Excel
                          </span>
                      </label>
                      <input type="file" class="d-none" id="fileInput" name="fileInput">
                      <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalTitle">Importar desde excel</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                Al importar nuevas compras desde excel, se sobreescribirán las compras que tengan el mismo campo ID.
                                  ¿Deseas continuar?
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                  <button type="submit" class="btn btn-primary" name="import">Importar desde excel</button>
                              </div>
                            </div>
                          </div>
                        </div>
                  </form>
              </div>

              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
    </div>
    <script>
        document.getElementById('id_fecha').type = 'date';
    </script>
    <script src="{% static 'main/assets/js/dashboard-import.js' %}" defer></script>
</div>

{% endblock %}

templates/dashboard/perfil.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load i18n %}

{% block main %}
<div class="container pt-5">
    <div class="row">
        <div class="col-1"></div>
        <div class="card card-primary card-outline col-10">
          <div class="card-body box-profile">
            <div class="text-center">
                {% if usuario.profile_pic %}
                    <img class="profile-user-img img-fluid img-circle" src="/media/{{ usuario.profile_pic }}" alt="User profile picture">
                {% else %}
                    <img class="profile-user-img img-fluid img-circle" src="{% static 'main/images/no_user.png' %}" alt="User profile picture">
                {% endif %}
            </div>

            <h3 class="profile-username text-center">{{ usuario.first_name }} {{ usuario.last_name }}</h3>

            <p class="text-muted text-center">{{ usuario.tipo_de_usuario }}</p>

            <ul class="list-group list-group-unbordered mb-3">
            {% if usuario.tipo_de_usuario == 'FOTOGRAFO' %}
              <li class="list-group-item">
                <b class="toggle-chk" id="listados" style="cursor: pointer;">Productos listados</b> <a class="float-right">{{ productos.count }}</a>
                  <div id="listados-show" style="display:none;">
                      <ul>
                          {% for producto in productos %}
                          <li><a href="{% url 'producto' id=producto.id %}">{{ producto }}</a></li>
                          {% endfor %}
                      </ul>
                  </div>
              </li>
              <li class="list-group-item">
                <b class="toggle-chk" id="vendidos" style="cursor: pointer;">Productos vendidos</b> <a class="float-right">{{ ventas.count }}</a>
                    <div id="vendidos-show" style="display:none;">
                      <ul>
                          {% for venta in ventas %}
                          <li><a href="{% url 'producto' id=venta.producto.id %}">{{ venta.producto }}</a></li>
                          {% endfor %}
                      </ul>
                  </div>
              </li>
            {% else %}
              <li class="list-group-item">
                <b class="toggle-chk" id="comprados" style="cursor: pointer;">Productos comprados</b> <a class="float-right">{{ compras.count }}</a>
                  <div id="comprados-show" style="display:none;">
                      <ul>
                          {% for compra in compras %}
                          <li><a href="{% url 'producto' id=compra.producto.id %}">{{ compra.producto }}</a></li>
                          {% endfor %}
                      </ul>
                  </div>
              </li>
              <li class="list-group-item">
                <b>Productos en lista de deseos</b> <a class="float-right">{{ wishlist }}</a>
              </li>
            {% endif %}
              <li class="list-group-item">
                <b>Reportes recibidos</b> <a class="float-right">
                  {% if denuncias.count < 3 %}
                  <strong style="color:green;">
                  {% elif denuncias.count < 8 %}
                  <strong style="color:orange;">
                  {% else %}
                  <strong style="color:red;">
                  {% endif %}
                      {{ denuncias.count }}
                  </strong>
              </a>
              </li>
            </ul>
            <form action="" method="POST"> {% csrf_token %}
                <a href="/perfil/{{ usuario.id }}" class="btn btn-primary"><b>Ver perfil en la web</b></a>
                    {% if usuario.is_active %}
                        <button type="submit" class="btn btn-danger float-right"><b>Desactivar usuario</b></button>
                    {% else %}
                        <button type="submit" class="btn btn-primary float-right"><b>Reactivar usuario</b></button>
                    {% endif %}
              </form>

          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/productos.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load i18n %}

{% block main %}

    <style>
        #id_user__username, #id_spot {
            height: 50px;
            border-radius: 5px;
            box-shadow: none;
            border: 1px solid gainsboro;
            padding-left: 10px;
            background: white;
        }

        #id_spot {
            width: 100%;
        }

        #id_fecha {
            width: 150px;
            height: 50px;
            border-radius: 5px;
            box-shadow: none;
            border: 1px solid gainsboro;
            background: white;
        }

    @media only screen and (max-width: 600px) {
        #filter_form, #col-form {
            left: 0 !important;
        }
    }

    </style>

    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">{% trans 'Home' %}</a></li>
              <li class="breadcrumb-item active">Gestión comercial</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="row">
            <div class="col-0 col-lg-2"></div>
            <div class="col-12 col-lg-4">
                  <div class="row mt-5">
                      <div class="col-12">
                        <div id="col-form" class="col-12" style=""><i class="fas fa-filter"></i> Filtrar</div>
                      </div>
                      <div class="col-12">
                          <a href="productos?area__pais__continente__nombre=EUROPA" class="nav-link">Productos de Europa</a>
                      </div>
                      <div class="col-12">
                           <a href="productos?area__pais__continente__nombre=AMERICA" class="nav-link">Productos de America</a>
                      </div>
                      <div class="col-12">
                            <a href="productos?area__pais__continente__nombre=AUSTRALIA AND NEW ZEALAND" class="nav-link">Productos de Australia & New Zealand</a>
                      </div>
                      <div class="col-12">
                          <a href="productos?area__pais__continente__nombre=ASIA" class="nav-link">Productos de Asia</a>
                      </div>
                      <div class="col-12">
                          <a href="productos?area__pais__continente__nombre=CARIBEAN" class="nav-link">Productos de Caribean</a>
                      </div>
                  </div>
            </div>

                <div class="col-12 col-lg-6">
                  <div class="row">
                      <div class="col-12 col-lg-6">
                        <form action="" method="POST" id="formulario" class="row">
                            {% csrf_token %}
                             <div class="col-12 mt-3">
                                 <label>{% trans 'Alias' %}*</label>
                                 <input type="text" name="alias" placeholder="Alias" class="form-control">
                             </div>

                            <div class="col-12 mt-3 d-none" id="div-cont">
                                <label>{% trans 'Continent' %}*</label>
                                <select name="" id="selectCont" class="form-control"></select>
                            </div>

                            <div class="col-12 mt-3" id="div-pais">
                                <label>{% trans 'Country' %}*</label>
                                <select name="" id="selectPais" class="form-control"></select>
                            </div>

                            <div class="col-12 mt-3">
                                <label>{% trans 'Area' %}*</label>
                                <select name="area" id="selectArea" class="form-control"></select>
                            </div>

                            <div class="col-12 mt-3">
                                <label>{% trans 'Spot' %}*</label>
                                <select name="spot" id="selectSpot" class="form-control"></select>
                            </div>

                            <input class="btn btn-primary mt-3" type="button" value="Filtrar productos" id="buscar">
                            <input class="btn btn-primary mt-3 d-none" type="submit" value="Elige qué estás buscando" name="filtro-productos" id="buscar-form">
                        </form>
                      </div>
                  </div>
                </div>
        </div>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Productos</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <ul class="products-list product-list-in-card pl-2 pr-2">
                  {% for producto in filter.qs %}
                    <li class="item">
                    <div class="product-img">
                      <img src="/media/{{ producto.imagen0 }}" alt="Product Image" class="img-size-50">
                    </div>
                    <div class="product-info">
                      <a href="{% url 'admin:home_producto_change' producto.id %}" class="product-title">{{ producto.nombre }}
                        <span class="badge badge-warning float-right">{{ producto.precio }} €</span></a>
                      <span class="product-description">
                        Publicado por <a href="{% url 'perfil_admin' id=producto.user.id %}">{{ producto.user }}</a>
                      </span>
                    </div>
                  </li>
                  {% endfor %}
                  <!-- /.item -->
                </ul>
              </div>
                <!-- /.card-body -->
             {% if user.is_superuser %}
              <div class="card-footer clearfix">

                        <a href="{% url 'admin:home_producto_add' %}" class="btn btn-sm btn-primary float-left">Añadir producto</a>
                        <a href="{% url 'admin:home_producto_changelist' %}" class="btn btn-sm btn-secondary float-right">Gestionar productos</a>

                  <form method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-sm btn-success float-left ml-3"> <i class="fas fa-file-export"></i>Exportar a Excel</button>
                  </form>

                  <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                      <label for="fileInput" style="cursor: pointer;">
                          <span class="btn btn-sm btn-info float-left ml-3">
                              <i class="fas fa-file-import"></i>Importar desde Excel
                          </span>
                      </label>
                      <input type="file" class="d-none" id="fileInput" name="fileInput">
                  </form>
              </div>
            {% endif %}
            </div>
        </div>
    </div>
</div>
 <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalTitle">Importar desde excel</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Al importar nuevos productos desde excel, sobreescribirán los productos que tengan el mismo campo ID.
              ¿Deseas continuar?
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-primary" name="import">Importar desde excel</button>
          </div>
        </div>
      </div>
    </div>
</div>


<script src="{% static 'main/assets/js/dashboard-import.js' %}" defer></script>

    <script defer>
            let scroll = "{{ scroll }}" === "True";

            const spotOG = {{ spotOG|safe }};

            let spotQS = [];

            for (let spot of spotOG) {
                var result = JSON.parse(spot)
                spotQS.push(result)
            }
    </script>

    <script src="{% static 'main/assets/js/buscador.js' %}" defer></script>
    <script src="{% static 'dashboard/filters.js' %}" defer></script>
    <script src="{% static 'main/assets/js/filtros-spots.js' %}" defer></script>



{% endblock %}